require("prototypes.equipment.equipment")
require("prototypes.item.emitter")
require("prototypes.entity.emitter")
require("prototypes.entity.spawner")
require("prototypes.recipes.emitter")
require("prototypes.technology.alien_defense")
